FROM tiangolo/uwsgi-nginx-flask:python3.11

# 设置工作目录
WORKDIR /app

# 安装额外的依赖
RUN pip install Flask-CORS==4.0.0 chardet==5.2.0 requests==2.31.0

# 复制应用代码
COPY backend/ ./backend/
COPY start.py ./
COPY frontend-vue/dist/ ./frontend-vue/dist/

# 暴露端口
EXPOSE 15000

# 启动命令  
CMD ["python", "backend/app.py"] 